/**
 * This class is generated by jOOQ
 */
package com.datn.ecm.jooq.model.tables.records;


import com.datn.ecm.jooq.model.tables.Clothes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClothesRecord extends UpdatableRecordImpl<ClothesRecord> implements Record14<Long, Long, String, Long, String, Double, String, Long, String, String, String, Double, String, String> {

    private static final long serialVersionUID = -1441235387;

    /**
     * Setter for <code>ecm_product.clothes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ecm_product.clothes.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ecm_product.clothes.color</code>.
     */
    public void setColor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.color</code>.
     */
    public String getColor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecm_product.clothes.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ecm_product.clothes.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ecm_product.clothes.discount</code>.
     */
    public void setDiscount(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.discount</code>.
     */
    public Double getDiscount() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>ecm_product.clothes.image</code>.
     */
    public void setImage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.image</code>.
     */
    public String getImage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ecm_product.clothes.last_modified</code>.
     */
    public void setLastModified(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.last_modified</code>.
     */
    public Long getLastModified() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>ecm_product.clothes.manufacture</code>.
     */
    public void setManufacture(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.manufacture</code>.
     */
    public String getManufacture() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ecm_product.clothes.material</code>.
     */
    public void setMaterial(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.material</code>.
     */
    public String getMaterial() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ecm_product.clothes.name</code>.
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.name</code>.
     */
    public String getName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ecm_product.clothes.price</code>.
     */
    public void setPrice(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.price</code>.
     */
    public Double getPrice() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>ecm_product.clothes.size</code>.
     */
    public void setSize(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.size</code>.
     */
    public String getSize() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ecm_product.clothes.sku</code>.
     */
    public void setSku(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>ecm_product.clothes.sku</code>.
     */
    public String getSku() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, Long, String, Double, String, Long, String, String, String, Double, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, Long, String, Double, String, Long, String, String, String, Double, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Clothes.CLOTHES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Clothes.CLOTHES.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Clothes.CLOTHES.COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Clothes.CLOTHES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Clothes.CLOTHES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Clothes.CLOTHES.DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Clothes.CLOTHES.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Clothes.CLOTHES.LAST_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Clothes.CLOTHES.MANUFACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Clothes.CLOTHES.MATERIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Clothes.CLOTHES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return Clothes.CLOTHES.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Clothes.CLOTHES.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Clothes.CLOTHES.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getLastModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getManufacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMaterial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value2(Long value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value3(String value) {
        setColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value4(Long value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value6(Double value) {
        setDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value7(String value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value8(Long value) {
        setLastModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value9(String value) {
        setManufacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value10(String value) {
        setMaterial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value11(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value12(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value13(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord value14(String value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClothesRecord values(Long value1, Long value2, String value3, Long value4, String value5, Double value6, String value7, Long value8, String value9, String value10, String value11, Double value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClothesRecord
     */
    public ClothesRecord() {
        super(Clothes.CLOTHES);
    }

    /**
     * Create a detached, initialised ClothesRecord
     */
    public ClothesRecord(Long id, Long categoryId, String color, Long createdAt, String description, Double discount, String image, Long lastModified, String manufacture, String material, String name, Double price, String size, String sku) {
        super(Clothes.CLOTHES);

        set(0, id);
        set(1, categoryId);
        set(2, color);
        set(3, createdAt);
        set(4, description);
        set(5, discount);
        set(6, image);
        set(7, lastModified);
        set(8, manufacture);
        set(9, material);
        set(10, name);
        set(11, price);
        set(12, size);
        set(13, sku);
    }
}
