/**
 * This class is generated by jOOQ
 */
package com.datn.ecm.jooq.model;


import com.datn.ecm.jooq.model.tables.Category;
import com.datn.ecm.jooq.model.tables.Clothes;
import com.datn.ecm.jooq.model.tables.Inventory;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EcmProduct extends SchemaImpl {

    private static final long serialVersionUID = -1783305936;

    /**
     * The reference instance of <code>ecm_product</code>
     */
    public static final EcmProduct ECM_PRODUCT = new EcmProduct();

    /**
     * The table <code>ecm_product.category</code>.
     */
    public final Category CATEGORY = com.datn.ecm.jooq.model.tables.Category.CATEGORY;

    /**
     * The table <code>ecm_product.clothes</code>.
     */
    public final Clothes CLOTHES = com.datn.ecm.jooq.model.tables.Clothes.CLOTHES;

    /**
     * The table <code>ecm_product.inventory</code>.
     */
    public final Inventory INVENTORY = com.datn.ecm.jooq.model.tables.Inventory.INVENTORY;

    /**
     * No further instances allowed
     */
    private EcmProduct() {
        super("ecm_product", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Clothes.CLOTHES,
            Inventory.INVENTORY);
    }
}
