/**
 * This class is generated by jOOQ
 */
package com.datn.ecm.jooq.model;


import com.datn.ecm.jooq.model.tables.Category;
import com.datn.ecm.jooq.model.tables.Clothes;
import com.datn.ecm.jooq.model.tables.Inventory;
import com.datn.ecm.jooq.model.tables.records.CategoryRecord;
import com.datn.ecm.jooq.model.tables.records.ClothesRecord;
import com.datn.ecm.jooq.model.tables.records.InventoryRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>ecm_product</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CategoryRecord, Long> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
    public static final Identity<ClothesRecord, Long> IDENTITY_CLOTHES = Identities0.IDENTITY_CLOTHES;
    public static final Identity<InventoryRecord, Long> IDENTITY_INVENTORY = Identities0.IDENTITY_INVENTORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_UK_46CCWNSI9409T36LURVTYLJAK = UniqueKeys0.KEY_CATEGORY_UK_46CCWNSI9409T36LURVTYLJAK;
    public static final UniqueKey<ClothesRecord> KEY_CLOTHES_PRIMARY = UniqueKeys0.KEY_CLOTHES_PRIMARY;
    public static final UniqueKey<ClothesRecord> KEY_CLOTHES_UK_3J4NXNCYQ0OSNIST7NMWXUDBD = UniqueKeys0.KEY_CLOTHES_UK_3J4NXNCYQ0OSNIST7NMWXUDBD;
    public static final UniqueKey<InventoryRecord> KEY_INVENTORY_PRIMARY = UniqueKeys0.KEY_INVENTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CategoryRecord, Long> IDENTITY_CATEGORY = createIdentity(Category.CATEGORY, Category.CATEGORY.ID);
        public static Identity<ClothesRecord, Long> IDENTITY_CLOTHES = createIdentity(Clothes.CLOTHES, Clothes.CLOTHES.ID);
        public static Identity<InventoryRecord, Long> IDENTITY_INVENTORY = createIdentity(Inventory.INVENTORY, Inventory.INVENTORY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = createUniqueKey(Category.CATEGORY, "KEY_category_PRIMARY", Category.CATEGORY.ID);
        public static final UniqueKey<CategoryRecord> KEY_CATEGORY_UK_46CCWNSI9409T36LURVTYLJAK = createUniqueKey(Category.CATEGORY, "KEY_category_UK_46ccwnsi9409t36lurvtyljak", Category.CATEGORY.NAME);
        public static final UniqueKey<ClothesRecord> KEY_CLOTHES_PRIMARY = createUniqueKey(Clothes.CLOTHES, "KEY_clothes_PRIMARY", Clothes.CLOTHES.ID);
        public static final UniqueKey<ClothesRecord> KEY_CLOTHES_UK_3J4NXNCYQ0OSNIST7NMWXUDBD = createUniqueKey(Clothes.CLOTHES, "KEY_clothes_UK_3j4nxncyq0osnist7nmwxudbd", Clothes.CLOTHES.SKU);
        public static final UniqueKey<InventoryRecord> KEY_INVENTORY_PRIMARY = createUniqueKey(Inventory.INVENTORY, "KEY_inventory_PRIMARY", Inventory.INVENTORY.ID);
    }
}
