/**
 * This class is generated by jOOQ
 */
package com.datn.ecm.jooq.model;


import com.datn.ecm.jooq.model.tables.Category;
import com.datn.ecm.jooq.model.tables.Clothes;
import com.datn.ecm.jooq.model.tables.Inventory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ecm_product
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ecm_product.category</code>.
     */
    public static final Category CATEGORY = com.datn.ecm.jooq.model.tables.Category.CATEGORY;

    /**
     * The table <code>ecm_product.clothes</code>.
     */
    public static final Clothes CLOTHES = com.datn.ecm.jooq.model.tables.Clothes.CLOTHES;

    /**
     * The table <code>ecm_product.inventory</code>.
     */
    public static final Inventory INVENTORY = com.datn.ecm.jooq.model.tables.Inventory.INVENTORY;
}
